package com.darksky.weather.today.weatherforecast.mainactivity.constant;


import com.darksky.weather.today.weatherforecast.R;

public class Const {

    public static String KEY = "";

    public static int[] weatherIcon = {
            R.drawable.ic_1,
            R.drawable.ic_2,
            R.drawable.ic_3,
            R.drawable.ic_4,
            R.drawable.ic_5,
            R.drawable.ic_5,
            R.drawable.ic_7,
            R.drawable.ic_8,
            R.drawable.ic_8,
            R.drawable.ic_8,
            R.drawable.ic_11,
            R.drawable.ic_12,
            R.drawable.ic_13,
            R.drawable.ic_13,
            R.drawable.ic_13,
            R.drawable.ic_13,
            R.drawable.ic_13,
            R.drawable.ic_12,
            R.drawable.ic_19,
            R.drawable.ic_20,
            R.drawable.ic_20,
            R.drawable.ic_19,
            R.drawable.ic_19,
            R.drawable.ic_24,
            R.drawable.ic_12,
            R.drawable.ic_12,
            R.drawable.ic_12,
            R.drawable.ic_12,
            R.drawable.ic_12,
            R.drawable.ic_30,
            R.drawable.ic_31,
            R.drawable.ic_4,
            R.drawable.ic_33,
            R.drawable.ic_32,
            R.drawable.ic_34,
            R.drawable.ic_34,
            R.drawable.ic_34,
            R.drawable.ic_34,
            R.drawable.ic_34,
            R.drawable.ic_13,
            R.drawable.ic_14,
            R.drawable.ic_14,
            R.drawable.ic_44,
            R.drawable.ic_44
    };

    public static int[] weatherIcon1 = {
            R.drawable.ic_icv_1,
            R.drawable.ic_icv_2,
            R.drawable.ic_icv_3,
            R.drawable.ic_icv_4,
            R.drawable.ic_icv_5,
            R.drawable.ic_icv_5,
            R.drawable.ic_icv_7,
            R.drawable.ic_icv_8,
            R.drawable.ic_icv_8,
            R.drawable.ic_icv_8,
            R.drawable.ic_icv_11,
            R.drawable.ic_icv_12,
            R.drawable.ic_icv_13,
            R.drawable.ic_icv_13,
            R.drawable.ic_icv_13,
            R.drawable.ic_icv_13,
            R.drawable.ic_icv_13,
            R.drawable.ic_icv_12,
            R.drawable.ic_icv_19,
            R.drawable.ic_icv_20,
            R.drawable.ic_icv_20,
            R.drawable.ic_icv_19,
            R.drawable.ic_icv_19,
            R.drawable.ic_icv_24,
            R.drawable.ic_icv_12,
            R.drawable.ic_icv_12,
            R.drawable.ic_icv_12,
            R.drawable.ic_icv_12,
            R.drawable.ic_icv_12,
            R.drawable.ic_icv_30,
            R.drawable.ic_icv_31,
            R.drawable.ic_icv_4,
            R.drawable.ic_icv_33,
            R.drawable.ic_icv_32,
            R.drawable.ic_icv_34,
            R.drawable.ic_icv_34,
            R.drawable.ic_icv_34,
            R.drawable.ic_icv_34,
            R.drawable.ic_icv_34,
            R.drawable.ic_icv_13,
            R.drawable.ic_icv_14,
            R.drawable.ic_icv_14,
            R.drawable.ic_icv_20,
            R.drawable.ic_icv_20
    };

}
